export { default as TrucksPage } from './pages/TrucksPage'
export { default as TruckForm } from './components/TruckForm'
export { default as TruckList } from './components/TruckList'
export { useTrucks } from './hooks/useTrucks'
export { useCreateTruck } from './hooks/useCreateTruck'
export { useUpdateTruck } from './hooks/useUpdateTruck'
export { useDeleteTruck } from './hooks/useDeleteTruck'
export { useTruck } from './hooks/useTruck'
export { useAvailableTrucks } from './hooks/useAvailableTrucks'
export { useTrucksWithDrivers } from './hooks/useTrucksWithDrivers'
export { useUploadTruckDocument } from './hooks/useUploadTruckDocument'
